### ISSUE TITLE
Question regarding JOSS paper authorship

### ISSUE THREAD

**Issue by jgonggrijp** [distant-viewing/dvt#12]
@statsmaths @nolauren @Nanne 

I'm currently reviewing the JOSS submission of `dvt` (https://github.com/openjournals/joss-reviews/issues/1800). One of the review criteria (per [JOSS documentation](https://joss.readthedocs.io/en/latest/review_criteria.html#authorship)) is that "the full list of paper authors seems appropriate and complete".

While I trust that the author list is correct, I am currently unable to objectively confirm this from the information available to me on GitHub:

- From the [paper](https://github.com/distant-viewing/dvt/blob/master/paper/paper.md), assuming I am looking at the right version, I find that the author list includes @nolauren and excludes @Nanne.
- From the [contributors graph](https://github.com/distant-viewing/dvt/graphs/contributors), the contributions by @Nanne *appear* to be more substantial than those by @nolauren. Both *appear* to be very small compared to the contributions by @statsmaths. Of course, I understand that this is only a measure of committed lines of code or text and that it completely disregards any contributions that may have been made outside of Git, including potentially important conceptual contributions.

Could you please clarify why @nolauren is included in the author list and why @Nanne is not? Please let me emphasize that I trust that there is a good reason; I'm just asking because this reason is currently invisible to me and I need it in order to confirm one of the review criteria. Thanks in advance.

**Comment by statsmaths** [comment]
Good question. We very much appreciate that @Nanne found the software useful and was willing to contribute two additional annotators to the toolkit. We hope that in the future other's will also want to contribute in this way as new methods and applications arise for the use of computer vision methods in the analysis of visual culture. The JOSS paper, however, is about the overall architecture and APIs exposed by the toolkit, which was solely the design and work of @nolauren and myself. Also, as you also mentioned, the contributes are a very limited proportion of the overall code-base.

The reason for including @nolauren as an author is two-fold. First, this is very much joint work that was initiated and produced collaboratively. We co-wrote and co-direct the lab and grant that supported the work, have co-run workshops focused on the design of the toolkit, and have each presented the toolkit and results using the toolkit at various conferences. Secondly, while the commit graph attributes nearly all of the code only to myself, many of the most important parts of the source code and documentation were actually written jointly in a pair-programming style while colocated at the University of Richmond. As the one with more Python experience, I was usually driving the computer and that's why most of the commits are tagged to me.

Hopefully that clarifies the disconnect between the commit graph and the authors. Please follow-up if more details are needed.

**Comment by jgonggrijp** [comment]
It does clarify and I'm satisfied. Thank you.
