### ISSUE TITLE
Annotator based on optical flow

### ISSUE THREAD

**Issue by Nanne** [distant-viewing/dvt#2]
Hi!

One of the annotators I would like to add to dvt is based on the optical flow between subsequent frames (with cv2's calcOpticalFlowFarneback). Yet, I'm not sure how to do this nicely, because for each batch it wouldn't be possible to calculate the optical flow for the last frame in the batch.

Additionally, in our project we segment a video into shots first, before analysing it, and then extract optical flow only for frames within the same shot, as the optical flow between two frames from different cuts is not very meaningful. I guess this can be solved during aggregation, where the frame before the cut is ignored (if necessary), but it would result in a decent amount of wasted computation for videos with many cuts..

Did you have any thoughts on what the 'right' way would be to deal with these kind of annotators within the dvt pipeline? I took a look at the DiffAnnotator, but that appears to be very 'batch oriented', which isn't always ideal I would think.

**Comment by statsmaths** [comment]
Adding optical flow would be a great contribution if you're willing to put it together!
It is possible to compute the optical flow for the last frame because each batch 
includes a look-ahead region (of equal size). That, for example, is how we are able
to do difference annotations. It is also possible to carry-over the key points to the
next batch using the cache attribute of the annotator. It doesn't seem like there would
be much wasted computation because even at a very high cut rate, cuts should only
be happen <5% of the time.

You are entirely correct that sometimes it is best to do a first past to get, e.g., cuts and
then run a second pass after having detected those cuts. This is entirely possible within
DVT. For example, you could

- run one pass with a cut annotator
- aggregate the cuts to get the shot breaks
- feed the shot breaks to initiate a new frame annotator
- re-run the pipeline

What's nice about that structure is that it is even possible to use a different program to
detect or manually specify the shot breaks before doing the optical flow.

**Comment by Nanne** [comment]
I didn't notice the look-ahead region, that's a clever solution! I'll have a go at adding optical flow then, as the structure definitely sounds flexible enough to make it work in a nice way, thanks!
