### ISSUE TITLE
DiffAnnotator/CutAggregator Not Functional for Black and White Films

### ISSUE THREAD

**Issue by mwrsh** [distant-viewing/dvt#24]
**Describe the bug**
DiffAnnotator and CutAggregator do not work with black and white films. I apologize if this is from lack of user knowledge, rather than a bug/missing feature.

**To Reproduce**
1. Run DataExtraction on a black and white movie file.
2. Run DiffAnnotator on the extracted data. The quantiles setting does not appear to have any effect.
3. Run CutAggregator(cut_vals={q[quantiles]: [value]})
4. No matter what the initial quantiles setting was, or the value run through the CutAggregator, any black and white clip is returned as being a single shot.

**Expected behavior**
Shots to be detected. This works perfectly fine with color film, but not at all for any black and white movie to which I have access.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2

**Comment by statsmaths** [comment]
From your message, what I understand is that when you run `DiffAnnotator` over your video file there are no detected differences in either the histogram or pixel-wise measures between successive frames. Is that correct? If that is the case, then clearly the issue is in the difference annotator and has nothing to do with the `CutAggregator` (detecting no cuts when there are no differences is the expected behavior).

We do know that detecting cuts is much more difficult with black and white images, particularly if there is a lot of movement or noise in the input data. However, there is no reason to expect to see no differences at all between frames. I just tested on a black-and-white input file that I have here and did not have any issue setting frame-over-frame differences with the `DiffAnnotator`. I wonder if the issue is something to do with different ways that black and white video files can be decoded by OpenCV (I just searched around in their documentation, but wasn't able to find anything specific to this problem). 

Have you tried to run any of the other annotators over your video file? In particular, I am curious if the `PngAnnotator` works as expected. You could also try `ColorHistogramAnnotator`. What I am trying to figure out is whether there is a more fundamental problem with decoding your video file. Perhaps the lower-level dvt code for extracting frames from video inputs is incorrectly assuming something that is incorrect for black and white video files.

Alternatively, if its possible to send (email is okay) a short clip of your video file containing a cut so that I can test is on my machine, that would be very helpful.

**Comment by mwrsh** [comment]
Thank you for your response. Here is the process I've gone through to illustrate the issue and show the results from the other annotators. For the data below, the clip I am working with is 30 seconds snipped from the middle of Stanley Kubrick's _The Killing_, which contains 5 shots.

`import argparse`

`from dvt.core import DataExtraction, FrameInput`
`from dvt.annotate.png import PngAnnotator`
`from dvt.annotate.diff import DiffAnnotator`
`from dvt.aggregate.cut import CutAggregator`
`from dvt.annotate.color import ColorHistogramAnnotator`
`import os`

`ap = argparse.ArgumentParser()`
`ap.add_argument('-f', '--filepath', type=str, required=True,`
`                               help='Path to the file directory.')`
`args = vars(ap.parse_args())`

`file_p = args['filepath']`

`out_path = os.path.join(os.path.dirname(file_p), 'png_out')`
`os.makedirs(out_path, exist_ok=True)`

`dextra = DataExtraction(FrameInput(input_path=file_p))`

`dextra.run_annotators([DiffAnnotator(quantiles=[40])])`
`print(dextra.get_data()['diff'])`

Result:
`      frame  avg_value  q40  h40`
`0         0  26.674997  0.0  0.0`
`1         1  26.694310  0.0  0.0`
`2         2  27.000117  0.0  0.0`
`3         3  27.276191  0.0  0.0`
`4         4  27.814587  0.0  0.0`
`...     ...        ...  ...  ...`
`1019   1019   0.000000  0.0  0.0`
`1020   1020   0.000000  0.0  0.0`
`1021   1021   0.000000  0.0  0.0`
`1022   1022   0.000000  0.0  0.0`
`1023   1023   0.000000  0.0  0.0`

So, we can see that there's no q40 nor h40 values, which I think (?) is expected behavior, since those would not be calculable in a black and white film.

For the sake of thoroughness, I run CutAggregator using the tutorial values:
`dextra.run_aggregator(CutAggregator(cut_vals={'q40': 3}))`
`print(dextra.get_data()['cut'])`

Result:
`   frame_start  frame_end`
`0            0       1023`

We then run CutAggregator using avg_value instead:
`dextra.run_aggregator(CutAggregator(cut_vals={'avg_value': 3}))`

Result:
`     frame_start  frame_end`
`0              0          0`
`1              1          1`
`2              2          2`
`3              3          3`
`4              4          4`
`...           ...        ...`
`896          896        896`
`897          897        897`
`898          898        898`
`899          899        899`
`900          900       1023`

Obviously that's not the right number of shots, but at least it's more than 0. Increasing the value from 3 to 10, 50, etc. decreases the number of detected shots, but not to any useful effect--it tends to produce shots that are a single frame long, and then a few that are many seconds long:
`dextra.run_aggregator(CutAggregator(cut_vals={'avg_value': 125}))`

Result:
`   frame_start  frame_end`
`0            0        739`
`1          740        740`
`2          741        741`
`3          742        742`
`4          743        743`
`5          744        744`
`6          745        745`
`7          746        746`
`8          747        747`
`9          748       1023`

PngAnnotator runs correctly.

Finally, ColorHistogramAnnotator. I set frequency to 30 to make sure I was getting clear differences between frames, rather than the relative similarity I'd see frame-to-frame. It seems to run perfectly correctly, as it is not just returning the same arrays for each frame:
`dextra.run_annotators([ColorHistogramAnnotator(freq=30)])`
`print(dextra.get_data()['colorhist'])`

Result:
`                                                  hsv  frame`
`0   [159286.0, 65417.0, 34933.0, 12459.0, 16540.0,...      0`
`1   [150836.0, 53452.0, 30962.0, 21264.0, 23508.0,...     30`
`2   [116298.0, 70521.0, 29720.0, 26216.0, 32674.0,...     60`
`3   [134549.0, 38701.0, 82742.0, 16055.0, 24787.0,...     90`
`4   [177826.0, 95539.0, 25844.0, 3290.0, 1851.0, 1...    120`
`5   [181588.0, 95447.0, 22408.0, 3070.0, 1850.0, 1...    150`
`6   [174196.0, 101423.0, 24341.0, 2745.0, 2457.0, ...    180`
`7   [108870.0, 121869.0, 17248.0, 10104.0, 11030.0...    210`
`8   [42719.0, 128350.0, 69233.0, 24626.0, 8115.0, ...    240`
`9   [41526.0, 126619.0, 70939.0, 27054.0, 9727.0, ...    256`
`10  [61139.0, 82572.0, 96095.0, 23954.0, 8788.0, 5...    286`
`11  [83446.0, 97850.0, 62089.0, 21152.0, 13848.0, ...    316`
`12  [107644.0, 106393.0, 59568.0, 15301.0, 7782.0,...    346`
`13  [100446.0, 72767.0, 54853.0, 16830.0, 13234.0,...    376`
`14  [66192.0, 95505.0, 120499.0, 10599.0, 3816.0, ...    406`
`15  [151188.0, 63592.0, 16341.0, 11166.0, 11214.0,...    436`
`16  [120713.0, 70728.0, 31191.0, 17105.0, 13709.0,...    466`
`17  [125345.0, 74420.0, 34112.0, 24118.0, 10789.0,...    496`
`18  [125177.0, 58379.0, 35181.0, 23743.0, 17125.0,...    512`
`19  [74996.0, 68153.0, 21246.0, 18823.0, 18978.0, ...    542`
`20  [48051.0, 53841.0, 24492.0, 20961.0, 18971.0, ...    572`
`21  [6991.0, 35217.0, 17288.0, 10073.0, 16077.0, 3...    602`
`22  [1390.0, 8581.0, 4808.0, 6968.0, 25871.0, 5862...    632`
`23  [2382.0, 8011.0, 4308.0, 10180.0, 51434.0, 951...    662`
`24  [1498.0, 4123.0, 5394.0, 24969.0, 97021.0, 999...    692`
`25  [916.0, 146.0, 6319.0, 38760.0, 38887.0, 25254...    722`
`26  [26481.0, 20308.0, 20470.0, 18913.0, 23712.0, ...    752`
`27  [31524.0, 28194.0, 25018.0, 19320.0, 23544.0, ...    768`
`28  [41090.0, 21227.0, 28485.0, 22573.0, 30896.0, ...    798`
`29  [30402.0, 43926.0, 18616.0, 19316.0, 47984.0, ...    828`
`30  [17605.0, 66316.0, 19419.0, 20137.0, 48507.0, ...    858`
`31  [25341.0, 36205.0, 28893.0, 26279.0, 46757.0, ...    888`
`32  [307200.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...    918`
`33  [307200.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...    948`
`34  [307200.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...    978`
`35  [307200.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   1008`

**Comment by statsmaths** [comment]
Thanks for the output and sending along a file to test with. It is a really good test case as it includes several different types of cuts.

**One-off solution**: I was able to get the cut detector working by using a very high quantile for the difference annotator. Here's the code I ran (using the 85 percentile and a cut-off of 16):

```
from dvt.core import DataExtraction, FrameInput
from dvt.annotate.diff import DiffAnnotator
from dvt.aggregate.cut import CutAggregator

file_p = "SK_TheKillingClip2.mp4"

dextra = DataExtraction(FrameInput(input_path=file_p))
dextra.run_annotators([DiffAnnotator(quantiles=[85])])
dextra.run_aggregator(CutAggregator(cut_vals={'q85': 16}))
dt = dextra.get_data()
```

The output of the cut detector is:

```
dt['cut']['time_start'] = dt['cut']['frame_start'] / dt['meta'].fps[0]
dt['cut']['time_end'] = dt['cut']['frame_end'] / dt['meta'].fps[0]
dt['cut']
```
```
   frame_start  frame_end  time_start   time_end
0            0        105    0.000000   3.503504
1          106        233    3.536870   7.774441
2          234        435    7.807808  14.514515
3          436        899   14.547881  29.996663
4          900       1023   30.030030  34.134134
```

Here, it detected three of the four cuts (the last one is a 'fake' cut that extends beyond the length of the actual video snippet). It is missing the cross-fade, which is not surprising because these are hard in general, but even more so when there is movement on both sides, and in black-and-white. I don't know of a simple way to get around this at the moment.

**Explantation**: The reason that you need a higher percentage in the difference annotator is this: we are comparing the difference between adjacent frames in HSV space. In black and white, the hue and saturation are always the same, so at a maximum only 1/3 of values can change. Will have to think about the best way to document this (or allow it to be adjusted) for black and white video files.

**Comment by mwrsh** [comment]
Thank you for looking into this. Since your solution should work for the majority of hard cuts, and the fade detection issue would be another can of worms, I consider this issue resolved, and will factor the increased quantile recommendation into my future DVT use.
